DDCE-4656 Replace cache for mongo caching
hmrc/pbik-frontend pull request #212
Opened 2023-10-18 07:45 UTC by gastonracui

2023-10-19 16:36 UTC, frikit commented
test this please!

2023-10-25 08:03 UTC, EdCope requested changes

2023-10-26 08:56 UTC, frikit commented on app/utils/ControllersReferenceData.scala
>          logger.warn(s"[ControllersReferenceData][responseErrorHandler] A NoSuchElementException was handled: $e0")
I will change warn to error and remove other one as that error log might log sensitive information and it will be a security issue

2023-10-26 09:03 UTC, frikit commented on app/services/SessionService.scala
> +    }
that method returns either to be able to handle in some place at this pnt in code if there is no session id I need to stop and I throw exception

2023-10-26 09:14 UTC, frikit commented on test/controllers/HomePageControllerSpec.scala
> +        val request: FakeRequest[AnyContentAsEmpty.type] = FakeRequest().withHeaders(
half of them need implicit other half dont, revert this change back so all have implicit

2023-10-26 11:40 UTC, EdCope approved these changes

2023-10-26 11:41 UTC, merged