DDCE-5001: Refactor generic connector methods and improve security
hmrc/pbik-frontend pull request #215
Opened 2023-12-18 16:46 UTC by EdCope

- Refactor generic methods from connector and split into specific calls
- Remove global var pbikHeaders for better security
- Move Bik values and strings to model to simplify regular remapping of data
- Upgraded to Scala 2.13.12 and updated dependencies

2023-12-18 16:57 UTC, EdCope commented
> * `uk.gov.hmrc.sbt-auto-build` can be updated to `3.17.0` in [project/plugins.sbt](https://github.com/hmrc/pbik-frontend/blob/DDCE-5001/project/plugins.sbt#L12)
> * There is a bobby warning (builds will be prevented after 31 May 2024) - see the pr builder for details

Both to be done with Play upgrade

2023-12-28 14:19 UTC, frikit requested changes

2023-12-28 14:19 UTC, frikit commented on app/connectors/HmrcTierConnector.scala
> +case class BikResponse(headers: Map[String, String], bikList: List[Bik])
move this to models package

2023-12-28 14:19 UTC, frikit commented on app/connectors/HmrcTierConnector.scala
> +case class EiLResponse(status: Int, eilList: List[EiLPerson])
move this to models package

2024-01-03 16:00 UTC, frikit approved these changes

2024-01-03 16:00 UTC, merged